
# backend/features/config.yaml
bands:
  - [0.001, 0.1]
  - [0.1, 1.0]
  - [1.0, 10.0]
vs_by_band_km_s:
  - 3.5
  - 3.5
  - 3.5
resonance:
  nperseg: 256
  min_energy_threshold: 1e-8
  mode_factor: 2.0
