
name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      NO_LIVE_FETCH: 1  # Use cache-only mode for CI
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libspatialindex-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python tests/triangulation/test_triangulation_integration.py
    
    - name: Check code structure
      run: |
        echo "Checking directory structure..."
        ls -la backend/services/ingest/
        ls -la experiments/tokyo/
        ls -la tests/triangulation/
    
    - name: Validate Python syntax
      run: |
        python -m py_compile backend/services/ingest/usgs_event_ingest.py
        python -m py_compile experiments/tokyo/experiment_driver.py
        python -m py_compile experiments/tokyo/triangulation_integration.py
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          experiments/tokyo/artifacts/
          tests/fixtures/
